<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>PassAccess</title>
</head>
<body>
<h1>Приложение для контроля пропуска</h1>

<form method="post" action="mainpage/signin">
    <input type="submit" value="Вход">
</form>

<form method="post" action="mainpage/signup">
    <input type="submit" value="Регистрация">
</form>

</body>
</html>